# Generated by Django 3.0.3 on 2020-09-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('userID', models.CharField(max_length=64)),
                ('job', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('priority', models.IntegerField(default=1000)),
                ('state', models.CharField(default='waiting', max_length=32)),
            ],
        ),
    ]
